add missing include (#2933)
Fixes build error with qt5 on Linux:

stellarium-1.2/plugins/MeteorShowers/src/MeteorShowersMgr.hpp:331:12:
 error: field 'm_lastUpdate' has incomplete type 'QDateTime'